### ISSUE TITLE
Error in the Error Console

### ISSUE THREAD

**Issue by welpdx** [whacked/zotero-special-tags-column#1]
The plugin works great. But if you goto the Error Console (Tools-> Developer -> Error Console), there's multiple errors of `"Error: Invalid field 'special-tags' for base field" {file: "Chrome://zotero/content/xpcom/data/itemFields.js" line: 280}`

This is a very minor issue

**Comment by whacked** [comment]
thanks for reporting this. I confirmed the same behavior in my zotero instance.

the errors appear if you launch zotero with the "Special Tags Column" visible in your main view. If you uncheck the column so it is hidden, then restart Zotero, the errors don't seem to show up in the log. If you re-show the column from the active Zotero session without the errors, showing the column doesn't cause the errors to appear.

So a guess as to the cause is some kind of initialization-time attribute reading logic in Zotero. Since this plugin uses a monkey patch method (copied from better-bibtex) maybe it's sneaking in an expected attribute without using a proper data registration process.

in any case, this is as far I got with looking at the problem, and it was quite annoying to see. Hopefully the update gets rid of it. Seems to have done the trick for me. Please re-open the issue if it's still showing up for you 🤞

**Comment by welpdx** [comment]
Hey thanks @whacked! I really appreciate you taking the time to taking a look at it. 

By the way, do you know how the monkey patch works? I want to try to add a custom column for [my noob add-on](https://github.com/welpdx/zotero-citationcounts) as well, but I am kinda confused at how it works. 
I can copy paste it and it will work but I rather understand it first. I see your implementation is different than how [scite](https://github.com/scitedotai/scite-zotero-plugin) for example. 

Anyways, thanks again!

Welp

**Comment by whacked** [comment]
at the micro level, starting from [this line](https://github.com/whacked/zotero-special-tags-column/blob/abe03d539c0aea0fcec2573e9be494dbb7180d38/chrome/content/zotero-special-tags-column.js#L39) the patch works by overriding a zotero-native `getCellText` method. You first store, then swap out the original method on the prototype, to do logic on the incoming object. In the case of this plugin, checking for the `zotero-item-column-special-tags` special property. If the special property isn't found, we fall back to the original `getCellText` method which happens on [this other line](https://github.com/whacked/zotero-special-tags-column/blob/abe03d539c0aea0fcec2573e9be494dbb7180d38/chrome/content/zotero-special-tags-column.js#L44)

I learned this ~hack~ technique from better bibtex, for example [here](https://github.com/retorquere/zotero-better-bibtex/blob/d410627fb2c45ad6aa3890541f3b256d488b998b/content/better-bibtex.ts#L317)

At the macro level I don't know what's going on: where the cell object comes from and where it goes.

**Comment by welpdx** [comment]
🙏🙏🙏
Thank you for your explanation! I understand your implementation now! It's ingenious! 

I'm new to js/ts so when I saw $patch$ and the monkeypatcher in bibtex, I was sooo confused. (with all the function exports and all that). The only info I had to go on were these [glitter msgs from retorquere](https://gitter.im/retorquere/zotero-better-bibtex?at=5bafbf6b1c100a4f29077ab5) lol. 

Thank you so much! And thanks for your time!
