### ISSUE TITLE
Feature request: show tags in a new row rather than column

### ISSUE THREAD

**Issue by woodwm** [whacked/zotero-special-tags-column#3]
Hi,

I always want to a way to show tags along each item in zotero to help me find it quickly. A good practice is the issue board in github. See the issues in Rust repository https://github.com/rust-lang/rust/issues.

![image](https://user-images.githubusercontent.com/13971199/168479935-9e388c3a-8cbd-4032-b07c-689c36c3f27e.png)

It is more clear than Zotero.

So I want to request a feature to show tags along the item like github issue. Something like the below. The item height is enlarged to show tags there. What do you think of this?

![image](https://user-images.githubusercontent.com/13971199/168479946-fbe50a7c-b0a1-49db-abe6-2eab035dd444.png)

**Comment by whacked** [comment]
hi thanks for the suggestion

In Zotero 5 I think this is a no-go. After updating the plugin to Zotero 6, I think this is actually possible, to a degree. I wrote some proof of concept code in https://github.com/whacked/zotero-special-tags-column/blob/main/chrome/content/zotero-special-tags-column.js#L226 but did not enable it.

It displays tags inline after the title text with custom styling.

<img width="488" alt="screenshot" src="https://user-images.githubusercontent.com/33410/168970652-386a6ed5-ae19-4ab4-9ca0-63692a7fe13b.png">

But since this plugin is almost entirely hacks right now, the functionality is best kept as small as possible. Until I have a need for this UI in my workflow, it's unlikely I will spend much more time on it.

A few thoughts after playing around with the proof of concept:
- zotero's own tag manager is a bit limiting (I have to merge a lot of `*TAG`, `TAG*`, `tag`, `Tag` duplicates), but doing beyond is significant effort; don't have a good solution now
- BUT it has a pretty good click-select, click-deselect interaction mode
- the first thing I want to do, when I see inline tags like your screenshot, is to click-select and click-deselect, and that's a lot more work
- I haven't tried putting tags into a 2nd line but I imagine it will massively expand the table and make it harder to scan (title row, tag row, title row, tag row)
- putting them inline leads to a cutoff, so you can't see all the tags at once
- to avoid the cutoff, you can it to maybe 3 "special tags" at most, so only the matching special tags show up
- in doing so, if want a quick visual scan of what special tags are matched, I would prefer them in a separate column, which is the current (minimum) functionality of this plugin, so I didn't see a substantial benefit of doing inline tags

that said, in Zotero 6 it is now possible to add a lot more fancy styling, including images, to the special tags. It's an interesting idea but I also haven't found a superior need for it yet. Maybe you can think of one.

**Comment by woodwm** [comment]
Hi,

Thanks. Columns in Zotero is already quite crowded and there is no much space to show full tags. Showing "special tags" is similar to the small colored square showing in front of titles for colored tags in Zotero. The number of colored tags are limited and you probably forget the meaning of colored tags easily. That is why I think showing the words of tags is important. 

I did not check where " `*TAG`, `TAG*`, `tag`, `Tag`" come from. I think only showing the user defined tags below the title is quite enough and I never use automatically generated tags.

It is good if tags below the titles are selectable, but showing tags for each item explicitly already help to locate the item. It is unclear whether showing tags  blow titles slow down the speed in quick visual scan. I guess if you have defined tags, tags should help you to remember what the paper is talking about and you probably focus more on tags than titles. As least for me, I cannot recall the content just from titles especially when it has been sometime since I read them.

Glad to know it is possible to do so.

**Comment by whacked** [comment]
I added support for CSS styling in the latest update. It's mainly to improve the visibility of the "ok" tag I use. So instead of using the 🆗 emoji, I now use a stylized "ok":

![](https://raw.githubusercontent.com/whacked/zotero-special-tags-column/main/doc/img/2022-05-20_Selection_001.png)

I don't know if this fits your use case but it *should* enable full word tags with colored backgrounds.

**Comment by whacked** [comment]
closing this as #wontfix for the following reasons:
- in the current add-on logic, showing tags as in your concept renderings can only be achieved -- if it is possible at all -- through CSS hacks, and I want to avoid more hacks
- Zotero 7 will overhaul the entire add-on architecture so bigger changes will lead to bigger maintenance effort when the switch happens

Thanks for the discussion
